apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: kube-ops
data:
  alertmanager.yml: |-

        # 全局配置项
        global:
          resolve_timeout: 5m # 处理超时时间，默认为5min
          smtp_from: 'fengshengjie@hotmail.com'
          smtp_smarthost: 'smtp.office365.com:588'
          smtp_auth_username: 'fengshengjie'
          smtp_auth_password: 'yourpassword'
          smtp_require_tls: false 

        # 定义路由树信息
        route:
          group_by: [alertname]  # 报警分组依据
          receiver: ops_notify   # 设置默认接收人
          group_wait: 30s        # 最初即第一次等待多久时间发送一组警报的通知
          group_interval: 60s    # 在发送新警报前的等待时间 下一次报警开车时间
          repeat_interval: 1h    # 重复发送告警时间。默认1h       第一次报警时间为group_interval  重复报警的时间为group_interval+repeat_interval
          routes:

          - receiver: ops_notify  # 基础告警通知
            group_wait: 10s
            match_re:
              alertname: 实例存活告警|磁盘使用率告警   # 匹配告警规则中的名称发送

          - receiver: info_notify  # 消息告警通知
            group_wait: 10s
            match_re:
              alertname: 内存使用率告警|CPU使用率告警

        # 定义基础告警接收者
        receivers:
        - name: ops_notify
          webhook_configs:
          - url: http://prometheus-webhook-dingtalk.ihaozhuo.com/dingtalk/ops_dingding/send
            send_resolved: true  # 警报被解决之后是否通知
          email_configs:
          - to: 'fengshengjie@hotmail.com‘
          # - to: 'it@hz-health.cn, xujiamin@hz-health.cn'  如果两个邮箱中间需要空格
            send_resolved: true

        # 定义消息告警接收者
        - name: info_notify
          webhook_configs:
          - url: http://prometheus-webhook-dingtalk.ihaozhuo.com/dingtalk/info_dingding/send
            send_resolved: true

        # 一个inhibition规则是在与另一组匹配器匹配的警报存在的条件下，使匹配一组匹配器的警报失效的规则。两个警报必须具有一组相同的标签。
        inhibit_rules:
          - source_match:
              severity: 'critical'
            target_match:
              severity: 'warning'
            equal: ['alertname', 'dev', 'instance']
