# apiVersion: v1
# kind: Namespace
# metadata:
#   name: sre

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: sre
  labels:
    app: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      # nodeSelector: 
      #   role: master
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:15.3.2-ce.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: gitlab80
        - containerPort: 443
          name: gitlab443
        - containerPort: 22
          name: gitlab22
        volumeMounts:
        - name: gitlab-config
          mountPath: /etc/gitlab
        - name: gitlab-log
          mountPath: /var/log/gitlab
        - name: gitlab-data
          mountPath: /var/opt/gitlab
      volumes:
      - name: gitlab-config
        hostPath:
          path: /opt/docker_data/gitlab/config
      - name: gitlab-log
        hostPath:
          path: /opt/docker_data/gitlab/log
      - name: gitlab-data
        hostPath:
          path: /opt/docker_data/gitlab/data

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: sre
spec:
  ports:
  - name: gitlab80
    protocol: TCP
    port: 80
    targetPort: gitlab80
  - name: gitlab443
    protocol: TCP
    port: 443
    targetPort: gitlab443
  - name: gitlab22
    protocol: TCP
    port: 22
    targetPort: gitlab22
  selector:
    app: gitlab

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-jason-com
  namespace: sre
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10240m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"

spec:
  ingressClassName: nginx
  rules:
  - host: gitlab.jason.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitlab
            port: 
              number: 80
