version: '2'

services:
  db:
    image: mariadb:10.4
    restart: always
    volumes:
      - /opt/docker_data/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:22.0
    restart: always
    ports:
      - 8099:80
    links:
      - db
    volumes:
      - /opt/docker_data/nextcloud/www:/var/www/html
